-- Migration: Add Folders Support

CREATE TABLE IF NOT EXISTS Folders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Recordings ADD COLUMN folderId INTEGER REFERENCES Folders(id) ON DELETE SET NULL;
